# Generated by Django 2.2.6 on 2019-10-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredient',
            field=models.ManyToManyField(to='pizza.Ingredient'),
        ),
    ]
